### ISSUE TITLE
Unable to install on HA Blue

### ISSUE THREAD

**Issue by jampez77** [OttPeterR/addon-babybuddy#1]
I get the following error when I try to install this add-on: Sorry for the screenshot, I'm on my phone.

I already have the baby buddy home assistant integration setup if that makes a difference. Currently running 2021.9.5

![Screenshot_20210913-220321_Home Assistant](https://user-images.githubusercontent.com/1823647/133156156-699e4374-1772-4fe7-a9d5-7950ca7e7428.jpg)

**Comment by OttPeterR** [comment]
I have my setup working on a Pi 4, what are you running? (I haven't tested other archs, sorry)

Also when I get around to having pre-built containers, this might resolve your issue, but I'm about to get busy with a kid so that could be in a long while...

**Comment by jampez77** [comment]
> I have my setup working on a Pi 4, what are you running? (I haven't tested other archs, sorry)
Ahh I'm on a HA blue, so maybe that's the issue. I currently run BB on a separate pi.
> I'm about to get busy with a kid so that could be in a long while...
I'm 4 weeks in the hole and haven't had time to do anything so yeah it will most likely be a long time haha. Stock up on your sleep while you can!

**Comment by OttPeterR** [comment]
Thanks for the advice and good luck to you too! Im awaiting my HA Blue to arrive so I'll hopefully have that working at some point as well.

**Comment by soonup** [comment]
Hi I get the same error. I am installing on hass.os running in a VM on an Intel Synology NAS.

**Comment by OttPeterR** [comment]
I've switched to HA Blue myself just now and I pushed some fixes that make it work on HA Blue (and hopefully other architectures as well)

let me know if it fixes it for your Synology NAS @soonup

**Comment by jampez77** [comment]
Good work! Hope the little one is well. Unfortunately this only got me one step further.

I've given it a quick go using the android app outside the house (using external URL) and after install I get a "page is not available" error message which then create the app.

Error message is;

'net:ERR_BLOCKED_BY_RESPONSE'

**Comment by OttPeterR** [comment]
Try setting the port in the config page, the ingress does not work properly yet because of some nginx issues but the opened port should work

**Comment by jampez77** [comment]
Ah ok, should it be a specific port?

**Comment by OttPeterR** [comment]
You have to enable it in the home assistant config of baby buddy, the default is 8000 but that is a common port so you can just pick whatever you want

**Comment by jampez77** [comment]
I've tried a few port options and appear to get stuck at `Starting NGinx`. Sorry to be such a pain haha.

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Baby Buddy
 Track sleep, feedings, diaper changes, tummy time and more!
-----------------------------------------------------------
 Add-on version: 1.9.0.1
 You are running the latest version of this add-on.
 System: Home Assistant OS 6.5  (aarch64 / odroid-n2)
 Home Assistant Core: 2021.10.6
 Home Assistant Supervisor: 2021.10.6
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] babybuddy.sh: executing... 
**** No secret key found, generating one ****
Operations to perform:
  Apply all migrations: admin, auth, authtoken, axes, babybuddy, contenttypes, core, easy_thumbnails, sessions
Running migrations:
  No migrations to apply.
  Your models in app(s): 'babybuddy' have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
Cache table 'cache_default' already exists.
[cont-init.d] babybuddy.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[09:07:12] INFO: NGINX waiting on babybuddy...
[2021-11-01 09:07:12 +0000] [374] [INFO] Starting gunicorn 20.1.0
[2021-11-01 09:07:12 +0000] [374] [INFO] Listening at: http://0.0.0.0:8000 (374)
[2021-11-01 09:07:12 +0000] [374] [INFO] Using worker: gthread
[2021-11-01 09:07:12 +0000] [404] [INFO] Booting worker with pid: 404
[2021-11-01 09:07:12 +0000] [405] [INFO] Booting worker with pid: 405
[09:07:12] INFO: Starting NGinx...
```

**Comment by OttPeterR** [comment]
That "stating NGINX" message should be the last thing you see in the console before it starts running - so maybe it's up just not accessible through your port for some reason..?

Try this to see if it's running: enable the "show in sidebar" option then click on the sidebar icon, does it make an error message shooter up in the baby buddy logs?

**Comment by jampez77** [comment]
I get this message when I try to access through the sidebar icon

`Not Found: /api/hassio_ingress/w3Ha1XIgUFrQ7-SlslH8_NBGCSP1NQp8Gj82AyEuqn0/`
 
Tried a few more ports with no joy, will keep trying.

**Comment by OttPeterR** [comment]
That "not found" message with the huge url means that baby buddy is running properly (even though it can't handle the ingress url)
Just to double check, you're setting the port in the home assistant baby buddy config to say 1234 then going to http://hassio.local:1234/ - right?

**Comment by jampez77** [comment]
ok so.... I can go straight to the URL with no problems but I get 'connection refused' when trying to access via HA.

**Comment by OttPeterR** [comment]
Okay great, that's how things are at the moment. I don't have NGINX configured properly to allow access directly through Home Assistant yet so only the URL access method works. 
(If you're an NGINX guru then I'd love some help!)

**Comment by jampez77** [comment]
Ah ok! Well in that case it works fine haha. I wish I could help as the main reason i want to safely access BB front end remotely. Hopefully it will be sorted some day in the future.

Hope I haven't wasted your time, thanks for your help.

**Comment by OttPeterR** [comment]
Happy to help! I'd like to get it to work through HA as well for the security of it. 

I'm going to close this issue for now since it installs on HA Blue now, but I'll ping you if/when I get NGINX working

**Comment by soonup** [comment]
> I've switched to HA Blue myself just now and I pushed some fixes that make it work on HA Blue (and hopefully other architectures as well)
> 
> let me know if it fixes it for your Synology NAS @soonup

thx, yes it's now working on a Synology Hassio VM as well. But as others have stated, the ingress does not work at the moment.
