### ISSUE TITLE
FR: using Docker linuxserver/docker-babybuddy ?

### ISSUE THREAD

**Issue by chpego** [OttPeterR/addon-babybuddy#17]
Would it be easier to use the [Docker provided by linuxserver](https://github.com/linuxserver/docker-babybuddy) ? rather than having to redo all the manual configuration in the docker to install BabyBuddy ?

I just tried to make a copy of the addon on my HA instance, and I injected the possibility to use the Docker directly, but I can't access from HA from the left panel; but I can access BabyBuddy via port 8000

**Comment by OttPeterR** [comment]
That's the reason I made its own image. Getting the port to be user-selectable and ingress (which will work some day! just not today haha) were the deciding factors in that. That said, I did essentially copy their Dockerfile to build the one I have when I first put this addon together, so it's nearly the same thing at the end of the day.
