### ISSUE TITLE
More efficent Baby buddy / Home Assistant backup possible ?

### ISSUE THREAD

**Issue by arekkusu** [OttPeterR/addon-babybuddy#20]
I am running Home Assistant with Baby buddy - as well as Grocy - as add-on and have automatic Home Assistant backup configured.

I noticed my Home Assistant backup are fairly large, slightly over 300MB (which add up fairly quickly when doing daily backup). Looking at the backup tar archive I noticed most of the space is used by "68152197_baby_buddy.tar.gz" (Baby Buddy add-on).

Within that Baby Buddy backup archive the actual data (database...) is a taking only a small amount of space. Most of the space by "image.tar" which contains the docker images used.

IMHO backing up all the docker images - which can be downloaded again - seem inefficient. I noticed that the "Grocy" add-on doesn't seem to suffer from the same issue in that its backup are taking much less space.

I don't know much about Home Assistant add-on architecture, I wondering if there is a reasonable way to avoid saving the docker image in backup. I realize this is more of an improvement request that an bug.

**Comment by OttPeterR** [comment]
Thanks for bringing this to my attention, I wasn't aware of the huge backup sizes haha

I don't know much about the details of how backups work but I'll look into it this weekend

**Comment by chpego** [comment]
@OttPeterR did you find a solution to be more efficent with backup ?
Maybe using the [**backup_exclude** option](https://developers.home-assistant.io/docs/add-ons/configuration/#optional-configuration-options) in addon ?

**Comment by chpego** [comment]
I found this in log:
``
22-11-13 08:56:19 INFO (SyncWorker_3) [supervisor.docker.addon] Export image 68152197/amd64-addon-baby_buddy to /data/tmp/tmp_jmj98j8/image.tar
``

**Comment by OttPeterR** [comment]
closing this issue, since switching over to pre-built add-ons, the backup size should be just a few MBs 😄
