### ISSUE TITLE
Using the USE_24_HOUR_TIME_FORMAT flag?

### ISSUE THREAD

**Issue by hugodejong** [OttPeterR/addon-babybuddy#22]
Is there a way to enable the 24-hour time format with this addon, like described in the Baby Buddy documentation here?https://docs.baby-buddy.net/configuration/application/#use_24_hour_time_format

I would really like to use BB in English but with a 24h format :)

**Comment by OttPeterR** [comment]
It shouldn't be too hard. Not promising I'll get it done soon, but since it's just and env var it sounds easy to do.

**Comment by hugodejong** [comment]
Thank you, I appreciate it. No rush, of course!

**Comment by OttPeterR** [comment]
this was an easy one, I finally got around to it 😅
you should see the update available soon!
