### ISSUE TITLE
Frequent "freezes"

### ISSUE THREAD

**Issue by jeroenterheerdt** [OttPeterR/addon-babybuddy#23]
Frequently the addon "freezes" - i.e. is not responsive anymore (webpage cannot be open). A simple restart does the trick. There is nothing in the addon logs, they look normal:
```
...
[02:21:46] INFO: NGINX waiting on babybuddy...
[2022-11-18 02:21:48 -0800] [201] [INFO] Starting gunicorn 20.1.0
[2022-11-18 02:21:48 -0800] [201] [INFO] Listening at: http://0.0.0.0:8000 (201)
[2022-11-18 02:21:48 -0800] [201] [INFO] Using worker: gthread
[2022-11-18 02:21:48 -0800] [241] [INFO] Booting worker with pid: 241
[2022-11-18 02:21:48 -0800] [242] [INFO] Booting worker with pid: 242
[02:21:48] INFO: Starting NGINX...
```

I am on Raspberry Pi 4, armv7 architecture.

**Comment by OttPeterR** [comment]
I've noticed this as well and I'm not sure what the cause it. Are you on iOS? (I am and this is where I see it happening, so maybe it's because of of an iOS reason)

**Comment by jeroenterheerdt** [comment]
Nope, I am on android, also seeing the same on pc. Restart of addon resolves it, but is annoying in the middle of the night 😂. I have reverted to the unsupported scenario of running babybuddy as container (stack) using the deprecated Portainer addon. Weirdly enough that never has the problem, albeit it's reported by ha as unsupported of course.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jeroenterheerdt** [comment]
@OttPeterR I noticed a new version of the addon, any chance you could let me know if this potentially solves the freezes?

**Comment by OttPeterR** [comment]
There's no changes specific to the freezes you're experiencing unfortunately. I thought some more about what you commented and that may be unique to your install. The freezes I get are only temporary in the PWA and clearing it fixes it (without a need for an addon restart).

**Comment by OttPeterR** [comment]
if you've been running an updated addon, have you seen the freezes recently?

**Comment by jeroenterheerdt** [comment]
freezes are definitely less, so let's close this issue for now.
