### ISSUE TITLE
Update issues

### ISSUE THREAD

**Issue by jwildman16** [OttPeterR/addon-babybuddy#25]
When I updated from 1.13.2.1 to 1.13.2.4, the update process effectively crashed Home Assistant. It became unresponsive. I could initiate an SSH session, but couldn't do anything after the initial connection. It seems like all the resources were tied up (I am currently running on an rPi3). I had tried this in the past and then resorted to restarting the host machine. This time, I let it run overnight and the update ended up being successful eventually. I'm running HA OS 9.3 and tried the update on two versions, 2022.11.1 and 2022.11.5. 

So, I don't have any current issues related to this but wanted to report it and see whether anyone else had a similar experience.

**Comment by OttPeterR** [comment]
I've experienced this issue when updating other HA addons when I used to run a Pi4, so my hunch is that it isn't uniquely a BB problem. That said, my best guess is that it's something related to locally building the docker image for the new version.

**Comment by OttPeterR** [comment]
@jwildman16 - has this happened for any of the recent updates?

**Comment by jwildman16** [comment]
> @jwildman16 - has this happened for any of the recent updates?

I've only gotten one update since and it did not happen. However, in the intervening time, I migrated my HA instance to a 2012 Mac Mini.

**Comment by jwildman16** [comment]
Should I close this as fixed?

**Comment by OttPeterR** [comment]
This may have been a one off, so I'll close it. But feel free to follow up if it happens again
