### ISSUE TITLE
Add Additional Config Option?

### ISSUE THREAD

**Issue by tango2590** [OttPeterR/addon-babybuddy#26]
It was mentioned on the main [BabyBuddy](https://github.com/babybuddy/babybuddy/issues/513#issuecomment-1345661739) repo that the Nap option is not currently a priority, but we could potentially disable it by adjusting `NAP_START_MAX` and `NAP_START_MIN`. Unfortunately, those variables aren't accessible using the HA add-on. Is it possible to add those to the add-on config to allow users to disable them until nap classification transitions from a half-baked to a full-baked feature?

**Comment by OttPeterR** [comment]
this was an easy one to implement, you should see the update be available shortly
