### ISSUE TITLE
DuckDNS / Ngix setup not exactly working as laid out in the instructions

### ISSUE THREAD

**Issue by kmanan** [OttPeterR/addon-babybuddy#29]
So, I'm not a Unix person and very much a n00b in this so please bear with me. I have HA running through duckdns on https://example.duckdns.org. I have setup baby Buddy Add-on using this repo and can access the Baby Buddy dashboard from within HA (https://example.duckdns.org/68152197_baby_buddy/dashboard). Throughout this process nowhere was I asked to enter a port (so the whole 8000 port thing in the instructions has been throwing me off). 

When I follow the steps in the instructions about the HTTPS https://github.com/OttPeterR/addon-babybuddy#additional-setup-for-https, my baby buddy setup doesn't work within HA. What I mean by that is the following:

For https://example.duckdns.org/68152197_baby_buddy/dashboard I have setup example.duckdns.org in the CSRF field.

For the https://babybuddy.example.duckdns.org/ setup, when I enter this in the csrf field, I can no longer go into my HA console though example.duckdns.org to access the baby buddy dashboard, I need to use babybuddy.example.duckdns.org (also, https isn't working even though nginx is setup).

In either case, even though I am able to get into the Baby Buddy dashboard, I am unable to authenticate the API key with this https://github.com/jcgoette/baby_buddy_homeassistant integration, keeps saying Invalid Authentication. This integration again asks for a port that so far I have only setup in nginx, nowhere else. Was hoping could any help in troubleshooting the key authentication issue.

Thanks

**Comment by OttPeterR** [comment]
I added a new part into the repository readme about setting the port, you should be able to find it in the BB addon configuration within HA, it's at the very bottom. The default is null to be more secure and not have ports just open, so it's something you'll need to set yourself, also port 8000 is potentially taken by some other service so you might need to pick something else.
