### ISSUE TITLE
add support: get history data (weight etc)

### ISSUE THREAD

**Issue by jetijeti** [OttPeterR/addon-babybuddy#32]
I am using the [Integration](https://github.com/jcgoette/baby_buddy_homeassistant) with imported data from another BB instance. So for example the weight is stored correctly in BB. But using the addon obviously only shows the data since the addon is used.

Now the idea is to somehow access this hisory data from BB to have the full history on weight/temperature/... data in HA available 

Can this be implemented?

P.S.
I started an [Issue](https://github.com/jcgoette/baby_buddy_homeassistant/issues/92)  in the integration which pointed me here

**Comment by OttPeterR** [comment]
I think it is not yet possible to add historical data into HA sensor. You can look into the 'statistics' table of HA if you're curious in learning more. I'll close this one out for now since it's a HA limitation.
