### ISSUE TITLE
Menu not appearing when accessing from within HA

### ISSUE THREAD

**Issue by Mamouti** [OttPeterR/addon-babybuddy#33]
When I try to access BB from within HA interface (Ingress), some button/menu content do not appear (see image below):
![IMG_20230115_164326](https://user-images.githubusercontent.com/75979814/212550972-9676acf5-c58c-4ab0-8e88-259989e4e81c.jpg)

However it does work when accessing the instance via its dedicated port.

I've tried reinstalling many times, to no avail. There is no errors in the logs (debug level).

This is not a cache or browser issue. I've tried on multiples devices, it never works when accessing from HA.

**Comment by OttPeterR** [comment]
This looks like it might be tricky, I'm not seeing anything on my end. Do any errors come up in a web console when you load the page and the issue happens?

**Comment by Mamouti** [comment]
I can see no error in the module logs, but maybe i'm not lokking at the right place ?

Maybe this can help?

>   bind: [':8000']
  backlog: 2048
  workers: 2
  worker_class: gthread
  threads: 4
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /app/babybuddy
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: /dev/shm
  user: 0
  group: 0
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: None
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: -
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: babybuddy.wsgi
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7fbb828670>
  on_reload: <function OnReload.on_reload at 0x7fbb828790>
  when_ready: <function WhenReady.when_ready at 0x7fbb8288b0>
  pre_fork: <function Prefork.pre_fork at 0x7fbb8289d0>
  post_fork: <function Postfork.post_fork at 0x7fbb828af0>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7fbb828c10>
  worker_int: <function WorkerInt.worker_int at 0x7fbb828d30>
  worker_abort: <function WorkerAbort.worker_abort at 0x7fbb828e50>
  pre_exec: <function PreExec.pre_exec at 0x7fbb828f70>
  pre_request: <function PreRequest.pre_request at 0x7fbb829090>
  post_request: <function PostRequest.post_request at 0x7fbb829120>
  child_exit: <function ChildExit.child_exit at 0x7fbb829240>
  worker_exit: <function WorkerExit.worker_exit at 0x7fbb829360>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7fbb829480>
  on_exit: <function OnExit.on_exit at 0x7fbb8295a0>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2023-01-15 16:40:57 +0100] [206] [INFO] Starting gunicorn 20.1.0
[2023-01-15 16:40:57 +0100] [206] [DEBUG] Arbiter booted
[2023-01-15 16:40:57 +0100] [206] [INFO] Listening at: http://0.0.0.0:8000 (206)
[2023-01-15 16:40:57 +0100] [206] [INFO] Using worker: gthread
[2023-01-15 16:40:57 +0100] [273] [INFO] Booting worker with pid: 273
[2023-01-15 16:40:57 +0100] [274] [INFO] Booting worker with pid: 274
[16:40:57] INFO:  [32mStarting NGINX... [0m
[2023-01-15 16:40:57 +0100] [206] [DEBUG] 2 workers
[2023-01-15 16:41:11 +0100] [273] [DEBUG] Ignored premature client disconnection. No more data after: b'\n'
[2023-01-15 16:41:12 +0100] [273] [DEBUG] GET /
[2023-01-15 16:41:16 +0100] [273] [DEBUG] Closing connection.
[2023-01-15 16:41:16 +0100] [273] [DEBUG] GET /dashboard/
[2023-01-15 16:41:18 +0100] [273] [DEBUG] Closing connection.
[2023-01-15 17:11:58 +0100] [274] [DEBUG] GET /
[2023-01-15 17:12:02 +0100] [274] [DEBUG] Closing connection.
[2023-01-15 17:12:03 +0100] [274] [DEBUG] GET /dashboard/
[2023-01-15 17:12:04 +0100] [274] [DEBUG] Closing connection.

It also is to be noted that I'm accessing my HA instance via https. I could not get the nginx instructions to work but figured it wouldn't be useful in my case as i do not need to access BB with a custom domain. I only wish to open it in HA.

**Comment by NobleWolf** [comment]
I'm also not seeing the issue in HA app on Android. I'm on the most recent
version of everything.
Let me know if you need other data for comparison.

**Comment by Mamouti** [comment]
Can you confirm you are using SSL with your HA instance (e.g https://yourowndomain.com:8123/), and you did NOT follow this procedure: https://github.com/OttPeterR/addon-babybuddy#additional-setup-for-https

**Comment by Mamouti** [comment]
Ok i'm a bit confused but found the issue, maybe it was a misunderstanding on my side. I declared the "INGRESS_USER" with a username from my HA instance (e.g "mathieu").
Setting this as "admin" fixed the issue! Maybe this requires a little clarification in the documentation for distracted users like me :) .

**Comment by michaellunzer** [comment]
this helped me too! 

+1 for putting "admin" as the ingress user made the "add a child" appear.
