### ISSUE TITLE
Multiple CSRF Trusted Origins

### ISSUE THREAD

**Issue by jampez77** [OttPeterR/addon-babybuddy#34]
I would like to set more than one CSRF Trusted Origins as different URLs are used by the HA companion apps depending on weather they are connected locally or remotely.

**Comment by OttPeterR** [comment]
It'll work if you use a comma (with no space)

Baby buddy has documentation [here](https://docs.baby-buddy.net/configuration/security/)

**Comment by OttPeterR** [comment]
I'll be updating the docs later today so I'll close this one out

**Comment by jampez77** [comment]
I missed the docs, apologies. 

However I'm still getting knocked back with comma separated hosts. Only the first host works, the second one after the comma doesn't work for me.

**Comment by OttPeterR** [comment]
I’m passing the content of that parameter to the baby buddy application, then I believe it’s giving that to Django, the django docs are [here](https://docs.djangoproject.com/en/4.0/ref/settings/#std:setting-CSRF_TRUSTED_ORIGINS) but these might not be much more additional help.I’m not familiar with how Django works so I wont be much help unfortunately 😞

edit: cleaning up email formatting
