### ISSUE TITLE
Measurements lack units

### ISSUE THREAD

**Issue by SpencerDub** [OttPeterR/addon-babybuddy#35]
It is unclear from the user interface what units, if any, are being used for each measurement, such as weight or height. On the one hand, that enables some flexibility, as two different users in different instances can use the units that work for them; on the other hand, it makes data analysis less than intuitive, as I have to remind myself that "8.0" means, "8 pounds" (for instance).

If I'm not overlooking something, can I request support for units be added?

**Comment by cdubz** [comment]
Yeah units are intentionally avoided so people can use whatever they want. It has been requested on occasion but not frequently enough to merit the added complexity. I'm open to arguments for it but generally I don't see any big advantages to having them.
