### ISSUE TITLE
Unable to update to 1.14

### ISSUE THREAD

**Issue by kmanan** [OttPeterR/addon-babybuddy#36]
Hi, I'm getting this error when I try to Install the update:

homeassistant.exceptions.HomeAssistantError: Error updating Baby Buddy: The command '/bin/bash -o pipefail -c echo "**** install build packages ****" && apk add --no-cache --virtual=build-dependencies build-base curl jpeg-dev libffi-dev libxml2-dev libxslt-dev postgresql-dev python3-dev zlib-dev' returned a non-zero code: 15

**Comment by jeroenterheerdt** [comment]
yes, exactly the same problem here!

**Comment by OttPeterR** [comment]
I need to create a docker image and push that out when an update comes out, but until I set that up these kind of issues keep happening unfortunately...

I know it's annoying, but try again in a day or two and the package dependency errors should resolve themselves, and that's how this issue has happened in the past.

**Comment by tj1816** [comment]
I see 1.15 is out, any chance on getting it pushed to the add-on?

**Comment by OttPeterR** [comment]
Just pushed 1.15.0

**Comment by OttPeterR** [comment]
reopening, there were some upgrade issues with v15, looking into the fix now...

**Comment by jwilters** [comment]
Hey @OttPeterR, I also get the same issue as mentioned at the start of this thread when trying to do a fresh install (not updating). We have a baby on the way in a month, so pretty keen to start playing around with this, hope you can help me get a fresh install running?

**Comment by OttPeterR** [comment]
Just pushed an update, let me know if it fixes the issue for you all 😃

**Comment by jwilters** [comment]
Thanks @OttPeterR, I've got Baby Buddy up and running on my Home Assistant!
