### ISSUE TITLE
Updating the Baby Buddy Addon

### ISSUE THREAD

**Issue by nbanderso** [OttPeterR/addon-babybuddy#39]
Hi. 

@cdubz was nice enough to add a new dashboard tile for pumping (details found [here](https://github.com/babybuddy/babybuddy/issues/601)).  

I noticed that Baby Buddy has been updated to reflect this new dashboard tile but not the HA addon.  Do you have an estimate on when this update will be pushed to those of us hosting Baby Buddy via Home Assistant?  

Thanks!

**Comment by OttPeterR** [comment]
Working on it, there's a migration issue causing an error but it'll be out hopefully in a week or so...

**Comment by cdubz** [comment]
@OttPeterR let me know if you need any help looking at that... I did some funky migration stuff in v1.15.0 😬

**Comment by Dis90** [comment]
Any news for update?

**Comment by OttPeterR** [comment]
Hey sorry, no news... but thanks for the reminder so I don't slack off 😆 
I'll not promise, but really try to start working on it this weekend

**Comment by OttPeterR** [comment]
Okay some news, I'm part way through making containers that'll make installing and updating much more reliable and fast. Not done yet though, so I appreciate the patience!

**Comment by OttPeterR** [comment]
Just pushed an update, let me know if it fixes the issue for you all 😃

**Comment by Dis90** [comment]
Just updated and works. Thank you 😊
