### ISSUE TITLE
Unable to install Baby Buddy in Home Assistant via Add-Ons

### ISSUE THREAD

**Issue by jwilters** [OttPeterR/addon-babybuddy#40]
Hi there, I have downloaded the repository and when clicking Install, I get the below error in Home Assistant:

The command '/bin/bash -o pipefail -c echo "**** install build packages ****" && apk add --no-cache --virtual=build-dependencies build-base curl jpeg-dev libffi-dev libxml2-dev libxslt-dev postgresql-dev python3-dev zlib-dev' returned a non-zero code: 15

Any idea how to solve this?

https://user-images.githubusercontent.com/96946602/228184217-61485468-bd34-4a09-af86-66d93cad2ec3.png

**Comment by OttPeterR** [comment]
Planning on looking into it this weekend, but may not have a fix out for a bit. This seems to be a transient issue and it may resolve itself if you try again at some point

**Comment by xelente** [comment]
Have the same issue, at first I thought it was something with my HA, so I tried installing it via a newly installed hass.io instance as well, but same issue there.

**Comment by rcjkierkels** [comment]
I have the same issue. Unable to install this addon

**Comment by OttPeterR** [comment]
Just pushed an update, let me know if it fixes the issue for you all 😃

**Comment by xelente** [comment]
> Just pushed an update, let me know if it fixes the issue for you all 😃

Seems to work, installed just fine! Thank you very much!
