### ISSUE TITLE
Missing sensors and switch after updating to HA 2023.8

### ISSUE THREAD

**Issue by Dis90** [OttPeterR/addon-babybuddy#53]
After updating to Home Assistant 2023.8 all sensors and switch are missing from device page.

> Logger: homeassistant.components.sensor
> Source: helpers/entity_platform.py:624
> Integration: Sensori ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
> First occurred: 09.17.56 (9 occurrences)
> Last logged: 09.17.56
> 
> Ignoring invalid device info: Invalid device info {'configuration_url': 'http://localhost:8000/children/leevi/dashboard/', 'default_name': 'Baby Leevi ', 'identifiers': {('babybuddy', 1)}} for 'babybuddy' config entry: device info needs to either describe a device, link to existing device or provide extra information.
> Ignoring invalid device info: Invalid device info {'configuration_url': 'http://localhost:8000/children/luka/dashboard/', 'default_name': 'Baby Luka ', 'identifiers': {('babybuddy', 2)}} for 'babybuddy' config entry: device info needs to either describe a device, link to existing device or provide extra information.

> Logger: homeassistant.components.switch
> Source: helpers/entity_platform.py:624
> Integration: Kytkin ([documentation](https://www.home-assistant.io/integrations/switch), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+switch%22))
> First occurred: 09.17.56 (2 occurrences)
> Last logged: 09.17.56
> 
> Ignoring invalid device info: Invalid device info {'default_name': 'Leevi ', 'identifiers': {('babybuddy', 1)}} for 'babybuddy' config entry: device info needs to either describe a device, link to existing device or provide extra information.
> Ignoring invalid device info: Invalid device info {'default_name': 'Luka ', 'identifiers': {('babybuddy', 2)}} for 'babybuddy' config entry: device info needs to either describe a device, link to existing device or provide extra information.

**Comment by OttPeterR** [comment]
I haven't updated yet so I'll follow up once I have, but in the meantime can you try going to the integration (in "Devices & Services", not the add-on) and see if a reload helps? I have a feeling this is an issue with the integration and not the add on but I'm not sure yet.

**Comment by OttPeterR** [comment]
Just updated, it seems like some sensors got renamed to end with a _2, you could open an issue about this over on [the integration page](https://github.com/jcgoette/baby_buddy_homeassistant)

**Comment by Dis90** [comment]
Yeah sorry. I got mixed with what sensors etc goes from integration and what from add-on.

Edit. There’s already issue opened in integration Github. So everything ok 😊

**Comment by OttPeterR** [comment]
No problem, thanks for being quick to raise an issue 👍
