### ISSUE TITLE
Missing Docker Images for various Arch

### ISSUE THREAD

**Issue by bembembene** [OttPeterR/addon-babybuddy#56]
Hello,
first my system. Homeassistant 9.1 . Installed the addon first over hacs. 
<img width="1012" alt="grafik" src="https://github.com/OttPeterR/addon-babybuddy/assets/54186348/e6bd9f3f-cc3c-4ab6-8b4f-af04845b9255">
 Tried to creat the integration in homeassistant and get this one : 
<img width="580" alt="grafik" src="https://github.com/OttPeterR/addon-babybuddy/assets/54186348/2503cf0c-4223-4795-9fff-ddeda70b4d01">
i haven't a clue what host, port, api key . cannot open any addon. Second try was to install it over Settings -> Add-ons -> Add-on Store and add this URL as an additional repository: get this window 
<img width="812" alt="grafik" src="https://github.com/OttPeterR/addon-babybuddy/assets/54186348/3a1997c1-d4f7-476d-a50b-30bdcfc87d7a">

thanks for helping... ben

**Comment by OttPeterR** [comment]
Seems like the ARM V7 image never built for the last few updates, I'll try and get it running again and send an update in this issue when it's done 😊

**Comment by bembembene** [comment]
thank you very much :)

**Comment by bembembene** [comment]
news?

**Comment by OttPeterR** [comment]
No news yet 😬

**Comment by Tjstock** [comment]
Yes please let me know if you end up getting it working. Just took home my little man and would love to try to get this integration :)

**Comment by bembembene** [comment]
congrats! :)

**Comment by SpeakingOfBrad** [comment]
I am also having this issue.  

And since I can't currently update to the latest version of BabyBuddy, I am missing most of the sensors in Home Assistant [https://github.com/jcgoette/baby_buddy_homeassistant/issues/127](https://github.com/jcgoette/baby_buddy_homeassistant/issues/127)  

![image](https://github.com/OttPeterR/addon-babybuddy/assets/824333/a1bd5478-c799-4456-a111-7a7c2430d3f6)

**Comment by OttPeterR** [comment]
I think I fixed this issue, the new containers should be building and ready in an hour or so 😄 
(you can check here to see when they're available: https://hub.docker.com/r/ottpeterr/)

**Comment by OttPeterR** [comment]
This was fixed but then some added dependencies have caused the single GitHub action that builds the containers to use too much storage, so its building in separate jobs now which should fix this issues for those seeing it again (should be fixed with #60 )
