### ISSUE TITLE
unable to update to new version.

### ISSUE THREAD

**Issue by LarsBorris** [OttPeterR/addon-babybuddy#62]
Hello,

When I try to update to the new version, this error occurs: (ver: 2.1.2)

Can't install ottpeterr/image-amd64-babybuddy:2.1.2: 404 Client Error for http+docker://localhost/v1.43/images/create?tag=2.1.2&fromImage=ottpeterr%2Fimage-amd64-babybuddy&platform=linux%2Famd64: Not Found ("manifest for ottpeterr/image-amd64-babybuddy:2.1.2 not found: manifest unknown: manifest unknown")

**Comment by OttPeterR** [comment]
😅 I forgot to publish the release, this'll get fixed once this action completes: https://github.com/OttPeterR/addon-babybuddy/actions/runs/6535630308

Sorry about that!

**Comment by OttPeterR** [comment]
It finished, you should be good to update 😄

**Comment by LarsBorris** [comment]
Ha ha alright :) it is monday after all :)
Nice work, it works now - verified!

Thanks!
