### ISSUE TITLE
Adding a CHANGELOG file

### ISSUE THREAD

**Issue by chpego** [OttPeterR/addon-babybuddy#65]
Maybe you can add an changelog file, and you can use this action : https://github.com/stefanzweifel/changelog-updater-action

**Comment by OttPeterR** [comment]
I've been meaning to do this, also to get it integrated into the HA UI to show what's new to the users. I'll try and get this going when I have a free moment. Thanks!

**Comment by OttPeterR** [comment]
Alright, these should be working now, its not automated since I'm going to put a link to the BB source repo in most cases, but you should see in here in GitHub and in Home Assistant 😄
