### ISSUE TITLE
Addon crashing with Error: s6-overlay-suexec: fatal: can only run as pid 1

### ISSUE THREAD

**Issue by cxy7722** [OttPeterR/addon-babybuddy#8]
A little new to this so forgive me if my question is really simple. 

I have installed the add-on and configured the port to access it via [http](http://homeassistant.local:8000/). I understand the ingress issue but was hoping the workaround would work for me, however, I realized the add on is crashing shortly after launch.

This is in the add-on logs:
s6-overlay-suexec: fatal: can only run as pid 1

I did find some other instances of this error here [http](https://community.home-assistant.io/t/latest-base-image-with-s6-overlay-v3-breaks-add-on/421570/3). Not sure if they are related or not.

**Comment by OttPeterR** [comment]
I'm able to recreate your issue, I'm working on a fix in addition to the new 1.11.0 baby buddy that was just released

**Comment by hindseb** [comment]
hi,
I just installed the add-on. But I am also getting the same error message in the logs.
's6-overlay-suexec: fatal: can only run as pid 1'

In addition, I am also getting a '502: Bad Gateway' error when trying to click on the web UI.
Any idea how to fix the errors?

**Comment by OttPeterR** [comment]
The web UI is broken (see issue #2) but you should be able to access it via the port you can set. That is of course assuming the s6 error is fixed. 

Could I ask what hardware you're running?

I haven't had much time to get into working on the fix unfortunately and not sure when I will.

**Comment by hindseb** [comment]
Hi
Thanks for the quick response.
I’m using a raspberry pi 4, 8gb

Let me know if you need further details.
I highly appreciate your efforts looking into this

Sebastian

**Comment by OttPeterR** [comment]
I pushed out an update, can some of you chime in if it fixes the launch issue?

**Comment by hindseb** [comment]
It works for me after updating. Thanks for your efforts. Highly appreciated!

**Comment by cxy7722** [comment]
Worked for me as well! Thank you!!

**Comment by OttPeterR** [comment]
closing this out, I believe it is no longer an issue
